core/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls")),
]


# Let django serve static files in development mode
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

core/main/urls.py
from django.urls import path
from .views import *

app_name = "main"
urlpatterns =[
    path('', BaseView.as_view(), name="base"),
    path('contact-us/',ContactUsView.as_view(), name="contact_us"),
    path('book-appointment/',AppointmentView.as_view(), name="appointment"), #noqa
]

core/main/models.py
from django.db import models

# Create your models here.
class Staff(models.Model):
	name= models.CharField(max_length=255)
	phone= models.CharField(max_length=15, default="0505757031")
	position = models.CharField(max_length=255)
	image = models.ImageField(upload_to="staff/")
	description = models.TextField()
	
	def __str__(self):
		return self.name
	



class Service(models.Model):
	name = models.CharField(max_length=255)
	description = models.TextField()
	image = models.ImageField(upload_to="services/")

	def __str__(self):
		return self.name
	

class Contact(models.Model):
	name= models.CharField(max_length=255)
	email = models.EmailField()
	phone = models.CharField(max_length=15)
	message = models.TextField()

	def __str__(self):
		return self.name



class Appointment(models.Model):
	customer_name = models.CharField(max_length=255)
	customer_meail = models.EmailField()
	customer_phone = models.CharField(max_length=15)
	service_type = models.CharField(max_length=255)
	date = models.DateField()
	time = models.TimeField()
	service = models.ForeignKey(Service, on_delete=models.CASCADE, null=True, blank= True)
	staff = models.ForeignKey(Staff, on_delete=models.CASCADE, null= True, blank=True)

	def __str__(self) -> str:
		return self.customer_name

core/main/forms.py
from django import forms
from .models import *

class ServiceForm(forms.ModelForm):
    class Meta:
        model = Service
        fields = "__all__"
        

class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = "__all__"
        
class StaffForm(forms.ModelForm):
    class Meta:
        model = Staff
        fields = "__all__"
        
class AppointmentForm(forms.ModelForm):
    class Meta:
        model= Appointment
        exclude = ["service", "staff"]
        

core/main/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.views import View


from main.models import Service, Staff
from .forms import AppointmentForm, ContactForm, StaffForm

# Create your views here.
class BaseView(View):
	template= "main/base.html"
	
	def get(self, request, *args, **kwargs):
		services = Service.objects.all()
		context ={
			"services":services,
		}
		return render(request, self.template, context)
	

class ContactUsView(View):
	def  get(self, request, *args, **kwargs):
		return redirect("main:base")
	
	def post(self, request, *args, **kwargs):
		form = ContactForm(request.POST)
		if form.is_valid():
			form.save()
			messages.success(request, 'Message Sent Successfully. You will hear from us soon!') #noqa
			return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
		else:
			for k, v in form.errors.items():
				messages.info(request, f'{k}:{v}')
				return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
			

class AppointmentView(View):
	template = 'main/appointment.html'

	def get(self, request, *args, **kwargs):
		staffs = Staff.objects.all()
		services = Service.objects.all()
		context ={
			"staffs": staffs,
			"services": services,
		}

		return render(request, self.template, context)
	
	def post(self, request, *args, **kwargs):
		staff_id = request.POST.get("staff_id")
		service_id = request.POST.get("service_id")
		staff = Staff.objects.filter(id=staff_id).first()
		service = Service.objects.filter(id=service_id).first()
		form = AppointmentForm(request.POST, request.FILES or None)
		if form.is_valid():
			appointment = form.save(commit=False)
			appointment.staff = staff
			appointment.service = service
			appointment.save()
			messages.success(request, 'Appointment Booked Successfully! We will get back to you') #noqa
			return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
		for k, v in form.errors.items():
			messages.infor(request, f'{k}: {v}')
			return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

core/main/templates/main/appointment.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>UltraSpa Spa and Salon | Home</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <style>
        body {
            font-family: Arial, sans-serif;
        }

        .jumbotron {
            background: url("{% static 'img/spa_img.jpg' %}") center/cover no-repeat;
            height: 100vh;
        }
    </style>
</head>

<body>
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <a class="navbar-brand" href="#">UltraSpa</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'main:base' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'main:base' %}#services">Services</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'main:base' %}#about">About Us</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'main:base' %}#contact">Contact</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <!-- alerts -->
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
        <center>{{message}}</center>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endfor %}
    {% endif %}

    <!-- Jumbotron / Hero Section -->
    <div class="jumbotron pt-4 row" style="overflow-y: scroll;">
        <section id="contact" class="col-12 col-md-6 mx-auto py-5 bg-light">
            <div class="container">
                <h2 class="text-center">Book Appointment</h2>
                <form method="POST" action="">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="name" class="form-label">Name</label>
                        <input type="text" name="customer_name" class="form-control" id="name" required>
                    </div>
                    <div class="mb-3">
                        <label for="email" class="form-label">Email</label>
                        <input type="email" name="customer_email" class="form-control" id="email" required>
                    </div>
                    <div class="mb-3">
                        <label for="phone" class="form-label">Phone</label>
                        <input type="text" name="customer_phone" class="form-control" id="phone" required>
                    </div>
                    <div class="mb-3">
                        <label for="message" class="form-label">Service Type</label>
                        <select name="service_type" class="form-control">
                            <option value="---">Select Service Type</option>
                            <option value="BASIC">BASIC</option>
                            <option value="DELUXE">DELUXE</option>
                            <option value="PREMIUM">PREMIUM</option>
                        </select>
                    </div>
                    <div class="mb-3">
                        <label for="staff_id" class="form-label">Staff</label>
                        <select name="staff_id" class="form-control">
                            <option value="---">Select Staff</option>
                            {% for staff in staffs %}
                            <option value="{{staff.id}}">{{staff.name}} - {{staff.position}}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="mb-3">
                        <label for="service" class="form-label">Service</label>
                        <select name="service" class="form-control">
                            <option value="---">Select Service</option>
                            {% for service in services %}
                            <option value="{{service.id}}">{{service.name}}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="mb-3">
                        <label for="date" class="form-label">Date</label>
                        <input type="date" name="date" class="form-control" id="date" required>
                    </div>
                    <div class="mb-3">
                        <label for="time" class="form-label">time</label>
                        <input type="time" name="time" class="form-control" id="time" required>
                    </div>
                    <button type="button" class="btn btn-primary" data-bs-toggle="modal"
                        data-bs-target="#confirmationModal" id="openConfirmationModal">Submit</button>

                </form>
            </div>
        </section>
        <section>
            <div class="my-5"></div>
        </section>
    </div>

    <!-- Footer Section -->
    <footer class="py-4 bg-dark text-white">
        <div class="container text-center">
            <p>&copy; 2023 UltraSpa. All rights reserved.</p>
            <ul class="list-inline">
                <li class="list-inline-item"><a href="#">Privacy Policy</a></li>
                <li class="list-inline-item"><a href="#">Terms of Service</a></li>
                <li class="list-inline-item"><a href="#">FAQ</a></li>
            </ul>
        </div>
    </footer>

    <!-- Modal -->
    <div class="modal fade" id="confirmationModal" tabindex="-1" aria-labelledby="confirmationModalLabel"
        aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="confirmationModalLabel">Confirm Appointment Details</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <p><strong>Name:</strong> <span id="modalCustomerName"></span></p>
                    <p><strong>Email:</strong> <span id="modalCustomerEmail"></span></p>
                    <p><strong>Phone:</strong> <span id="modalCustomerPhone"></span></p>
                    <p><strong>Service Type:</strong> <span id="modalServiceType"></span></p>
                    <p><strong>Staff:</strong> <span id="modalStaff"></span></p>
                    <p><strong>Service:</strong> <span id="modalService"></span></p>
                    <p><strong>Date:</strong> <span id="modalDate"></span></p>
                    <p><strong>Time:</strong> <span id="modalTime"></span></p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                    <button type="button" class="btn btn-primary" id="submitAppointment">Confirm & Submit</button>
                </div>
            </div>
        </div>
    </div>


    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
        integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
        integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous">
    </script>

    <script>
        document.getElementById("openConfirmationModal").addEventListener("click", function () {
            // Get the selected values from the form
            const customerName = document.getElementById("name").value;
            const customerEmail = document.getElementById("email").value;
            const customerPhone = document.getElementById("phone").value;
            const serviceType = document.querySelector('select[name="service_type"]').value;
            const staff = document.querySelector('select[name="staff_id"]').options[document.querySelector(
                'select[name="staff_id"]').selectedIndex].text;
            const service = document.querySelector('select[name="service"]').options[document.querySelector(
                'select[name="service"]').selectedIndex].text;
            const date = document.getElementById("date").value;
            const time = document.getElementById("time").value;

            // Set the selected values in the modal
            document.getElementById("modalCustomerName").innerText = customerName;
            document.getElementById("modalCustomerEmail").innerText = customerEmail;
            document.getElementById("modalCustomerPhone").innerText = customerPhone;
            document.getElementById("modalServiceType").innerText = serviceType;
            document.getElementById("modalStaff").innerText = staff;
            document.getElementById("modalService").innerText = service;
            document.getElementById("modalDate").innerText = date;
            document.getElementById("modalTime").innerText = time;

            // Show the modal
            const myModal = new bootstrap.Modal(document.getElementById('confirmationModal'), {});
            myModal.show();
        });

        // Handle form submission
        document.getElementById("submitAppointment").addEventListener("click", function () {
            // Submit the form
            document.querySelector("form").submit();
        });
    </script>

</body>

</html>

core/main/templates/main/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>UltraSpa Spa and Salon | Home</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <style>
        body {
            font-family: Arial, sans-serif;
        }

        .jumbotron {
            background: url("{% static 'img/spa_img.jpg' %}") center/cover no-repeat;
            /* background: url('oil_img.jpg') center/cover no-repeat; */
            height: 80vh;
        }
        
    </style>
</head>

<body>
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <a class="navbar-brand" href="#">UltraSpa</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="#">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#services">Services</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#about">About Us</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#contact">Contact</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <!-- alerts -->
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
        <center>{{message}}</center>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endfor %}
    {% endif %}

    <!-- Jumbotron / Hero Section -->
    <div class="jumbotron pt-4">
        <div class="container text-center text-white my-auto py-auto">
            <h1 class="display-4">Welcome to <span style="color: blueviolet;">UltraSpa</span> </h1>
            <p class="lead">Indulge in the ultimate relaxation experience</p>
            <a href="{% url 'main:appointment' %}" target="_blank" class="btn btn-primary btn-lg">Book Now</a>
        </div>
    </div>

    <!-- Services Section -->
    <section id="services" class="py-5 bg-light">
        <div class="container">
            <h2 class="text-center">Our Services</h2>
            <div class="services-scroll-wrapper">
                <div class="row">
                    <div class="col-md-4">
                        <div class="card mb-4">
                            <img src="{% static 'img/massage_img.jpg' %}" class="card-img-top" alt="Massage Service">
                            <div class="card-body">
                                <h5 class="card-title">Massage</h5>
                                <p class="card-text">Relax your body and mind with our soothing massage treatments.</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="card mb-4">
                            <img src="{% static 'img/facial_img2.jpg' %}" class="card-img-top" alt="Facial Service">
                            <div class="card-body">
                                <h5 class="card-title">Facial</h5>
                                <p class="card-text">Rejuvenate your skin with our specialized facial treatments.</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="card mb-4">
                            <img src="{% static 'img/mancure_img.jpg' %}" class="card-img-top" alt="Manicure Service">
                            <div class="card-body">
                                <h5 class="card-title">Manicure</h5>
                                <p class="card-text">Pamper yourself with our expert manicure services.</p>
                            </div>
                        </div>
                    </div>
                    {% for service in services %}
                    <div class="col-md-4">
                        <div class="card mb-4">
                            <img src="{% if service.image %}{{service.image.url}}{% else %}{% static 'img/mancure_img.jpg' %}{% endif %}"
                                class="card-img-top" alt="{{service.name}} Services">
                            <div class="card-body">
                                <h5 class="card-title">{{service.name}}</h5>
                                <p class="card-text">{{service.description}}</p>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </section>

    <!-- About Us Section -->
    <section id="about" class="py-5">
        <div class="container">
            <h2 class="text-center">About Us</h2>
            <p>Welcome to UltraSpa Spa & Salon, where tranquility meets beauty. Step into a world of pure relaxation
                and rejuvenation, where our expert therapists and stylists curate bespoke experiences tailored to your
                needs. Immerse yourself in a sanctuary of soothing treatments, designed to invigorate the senses and
                restore balance to your mind, body, and soul. Unwind and embrace the harmony as we take you on a
                transformative journey to unveil your true beauty. At UltraSpa, we believe that self-care is an art,
                and our mission is to make you feel exquisite, both inside and out. Discover the blissful haven you've
                been searching for – your ultimate escape awaits.</p>
        </div>
    </section>

    <!-- Contact Section -->
    <section id="contact" class="py-5 bg-light">
        <div class="container">
            <h2 class="text-center">Contact Us</h2>
            <form method="POST" action="{% url 'main:contact_us' %}">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="name" class="form-label">Name</label>
                    <input type="text" name="name" class="form-control" id="name" required>
                </div>
                <div class="mb-3">
                    <label for="email" class="form-label">Email</label>
                    <input type="email" name="email" class="form-control" id="email" required>
                </div>
                <div class="mb-3">
                    <label for="phone" class="form-label">Phone</label>
                    <input type="text" name="phone" class="form-control" id="phone" required>
                </div>
                <div class="mb-3">
                    <label for="message" class="form-label">Message</label>
                    <textarea class="form-control" name="message" id="message" rows="4" required></textarea>
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </section>

    <!-- Pricing Section -->
    <section id="pricing" class="py-5">
        <div class="container">
            <h2 class="text-center">Pricing</h2>
            <div class="row">
                <div class="col-md-4">
                    <div class="card mb-4">
                        <div class="card-header bg-primary text-white">
                            <h5 class="card-title">Basic Package - Ultra Delight</h5>
                        </div>
                        <div class="card-body">
                            <h6 class="card-subtitle mb-2 text-muted">30-Minute Massage</h6>
                            <p class="card-text">Indulge in the bliss of our <span style="color: blueviolet;">Ultra
                                    Delight</span> package,
                                offering a
                                30-minute soothing massage that will melt away your stress and tensions. Let our skilled
                                therapists work their magic, leaving you refreshed and rejuvenated. Immerse yourself in
                                a state of pure tranquility as you unwind in the calming ambiance of our spa.
                            </p>
                            <ul>
                                <li class="li">30-Minute Relaxing Massage</li>
                                <li class="li"> Aromatherapy with Essential Oils</li>
                                <li class="li"> Complimentary Refreshments</li>
                                <li class="li"> Access to Sauna, swimming pool and Steam Room</li>
                            </ul>
                            <p class="card-text">Price: $50</p>
                            <a href="{% url 'main:appointment' %}" target="_blank" class="btn btn-primary">Book Now</a>
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="card mb-4">
                        <div class="card-header bg-info text-white">
                            <h5 class="card-title">Deluxe Package - Renewal Escape</h5>
                        </div>
                        <div class="card-body">
                            <h6 class="card-subtitle mb-2 text-muted">60-Minute Massage + Facial</h6>
                            <p class="card-text">Experience the ultimate pampering with our Renewal Escape package, a
                                delightful combination of a 60-minute massage and a luxurious facial. Let your worries
                                drift away as our expert masseuses ease your muscles with skillful hands, while our
                                skilled estheticians work their magic on your skin, leaving it radiant and glowing.
                            </p>
                            <ul>
                                <li class="li">60-Minute Massage of Your Choice</li>
                                <li class="li">Luxurious Facial Treatment</li>
                                <li class="li">Complimentary Herbal Tea Infusion</li>
                                <li class="li">Access to Sauna, Steam Room, and Jacuzzi</li>
                            </ul>
                            <p class="card-text">Price: $100</p>
                            <a href="{% url 'main:appointment' %}" target="_blank" class="btn btn-info">Book Now</a>
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="card mb-4">
                        <div class="card-header bg-success text-white">
                            <h5 class="card-title">Premium Package - Harmony</h5>
                        </div>
                        <div class="card-body">
                            <h6 class="card-subtitle mb-2 text-muted">90-Minute Massage + Facial + Manicure</h6>
                            <p class="card-text">Embark on a harmonious journey with our Harmony Serenade package, a
                                divine symphony of indulgence featuring a 90-minute massage, luxurious facial, and
                                expert manicure. Our master therapists will orchestrate an exquisite experience that
                                soothes your senses and brings deep relaxation to every inch of your body.
                            </p>
                            <ul>
                                <li class="li">90-Minute Signature Massage</li>
                                <li class="li">Rejuvenating Facial with Skincare</li>
                                <li class="li">Expert Manicure with Nail Art</li>
                                <li class="li">Complimentary Glass of Champagne</li>
                                <li class="li">Access to Sauna, Jacuzzi, and Pool</li>
                            </ul>
                            <p class="card-text">Price: $150</p>
                            <a href="{% url 'main:appointment' %}" target="_blank" class="btn btn-success">Book Now</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- Footer Section -->
    <footer class="py-4 bg-dark text-white">
        <div class="container text-center">
            <p>&copy; 2023 UltraSpa. All rights reserved.</p>
            <ul class="list-inline">
                <li class="list-inline-item"><a href="#">Privacy Policy</a></li>
                <li class="list-inline-item"><a href="#">Terms of Service</a></li>
                <li class="list-inline-item"><a href="#">FAQ</a></li>
            </ul>
        </div>
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
        integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
        integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous">
    </script>

    <script>
    </script>
</body>

</html>